name: TableTool publish
on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "auto_merge_enabled"
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm i pnpm -g
          pnpm i
          pnpm run -C doc docs:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: docs # The branch the action should deploy to.
          folder: doc/docs/.vitepress/dist # The folder the action should deploy.