name: TableTool publish
on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "auto_merge_enabled"
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: main
        FOLDER: doc/docs/vitepress/dist
        BUILD_SCRIPT: npm i pnpm -g && npm install &&  npm run -C doc docs:build